apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-nest-analytics
spec:
  replicas: 3
  selector:
    matchLabels:
      name: local-nest-analytics
  template:
    metadata:
      labels:
        name: local-nest-analytics
    spec:
      containers:
      - name: app
        image: local-nest-analytics
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
            name: http
          - containerPort: 3010
            name: tcp