apiVersion: v1
kind: Service
metadata:
  name: local-nest-communication
spec:
  type: LoadBalancer
  ports:
  - port: 3021
    targetPort: 3010
    protocol: TCP
  selector:
    name: local-nest-communication